spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/xx?serverTimezone=Asia/Shanghai&useUnicode=true&useAffectedRows=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  elasticsearch:
    rest:
      uris: "http://192.168.33.88:9200"
server:
  port: 3333
